### PR TITLE
Add tests config for Kubernetes based CI

### PR DESCRIPTION
**Pull request by plirglo**
These changes are necessary to run tests on Kubernetes based build system.

Kubernetes based build system means that build agents work inside Kubernetes cluster. During testing process docker container with application is created. This means that we've got "docker inside docker (DiD)". This kind of environment requires a bit different configuration of mount shared storage to docker container than with standard one-layer configuration.

With DiD configuration shared volume needs to be created on host machine and this volume is shared with application container. 
To create volume use below configuration as template:

```
spec:
  template:
    spec:
      containers:
        volumeMounts:
        - mountPath: /tests-share # kubernetes volume
          name: tests-share
      volumes:
      - name: tests-share
        hostPath:
          path: /tmp/tests-share # hosts' shared location
```

To use this config just setup two variables on you build agent's system:
```
export AZBI_K8S_VOL=/tests-share
export AZBI_MOUNT=/tmp/tests-share
```
These parameters let tests.sh script recognize that is running on Kubernetes CI system.

### CODE REVIEW

**Comment by pprach** [comment]
Let's see ~how far we've come~ if it will trigger after this comment

**Review by mkyc — CHANGES_REQUESTED** [review]
Nice, cay you just add description how to setup test environment if I'd like to test it on Minikube for example?

**Comment by plirglo** [comment]
> Nice, cay you just add description how to setup test environment if I'd like to test it on Minikube for example?

I'm not sure how it will work on minikube, but in standard kubernetes cluster you need to:
1.  Create volume  (host path), in deployment.yaml add this config to create kubernetes volume:
```
volumes:
- name: tests-share
  hostPath:
    path: /tmp/tests-share
```
See manual for more details: https://kubernetes.io/docs/concepts/storage/volumes/#hostpath

2. Add mount point for your kubernetes pod, in deployment.yaml add this config to define where it will be mounted:
```
volumeMounts:
- mountPath: /tests-share
  name: tests-share
```
3. Inside pod where you run tests setup two variables:
```
export AZBI_K8S_VOL=/tests-share
export AZBI_MOUNT=/tmp/tests-share  ##modify paths according your needs, but they need to match paths from steps 1 and 2.
```
4. Go to location where you downloaded repository and run:
```
make test
```
5. Test results will be availabe inside ```/tmp/tests-share``` on node on which pod is running.

**Comment by mkyc** [comment]
Yeah, can you add it to some subsection in readme?

**Comment by plirglo** [comment]
> Yeah, can you add it to some subsection in readme?

Added to README.md

**Review by mkyc — DISMISSED** [review]
LGTM

**Review by mkyc — APPROVED** [review]

**Review by sk4zuzu — APPROVED** [review]
LGTM

**Pull request merged**
